version: "3.9"  # optional since v1.27.0
services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    networks:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    image: test2
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/wp
    depends_on:
      - database

  database:
    image: "postgres"
    networks:
      - backend
    env_file:
      - database.env
    ports:
      - "5432:5432"

networks:
  backend:
    driver: bridge
